export enum ProductMSG {
  STORE = 'CREATE_PRODUCT',
  INDEX = 'FIND_PRODUCTS',
  INDEX_BY_CATEGORY = 'FIND_BY_CATEGORY_PRODUCTS',
  SHOW = 'FIND_PRODUCT',
  UPDATE = 'UPDATE_PRODUCT',
  DESTROY = 'DELETE_PRODUCT',
}
